adding my info to metadata.json
PoisotLab/ms_network_prediction pull request #15
Opened 2020-10-30 19:25 UTC by gottacatchenall

2020-10-30 19:29 UTC, tpoisot approved these changes

2020-10-30 19:32 UTC, TanyaS08 requested changes
Reorder - needs to be listed in same order as issues. 🐾

2020-10-30 19:34 UTC, gottacatchenall reviewed
flipped the order around

2020-10-30 19:35 UTC, TanyaS08 approved these changes
🌟

2020-10-30 19:44 UTC, tpoisot requested changes

2020-10-30 19:44 UTC, tpoisot commented on metadata.json
> +      "email": "michael.catchen@mail.mcgill.ca",
remove the email for now

2020-10-30 19:45 UTC, gottacatchenall reviewed
email removed

2020-10-30 19:46 UTC, TanyaS08 approved these changes
⭐

2020-10-31 01:21 UTC, tpoisot approved these changes

2020-10-31 01:21 UTC, merged