✏️
PoisotLab/ms_network_prediction pull request #17
Opened 2020-10-30 19:54 UTC by TanyaS08

added placeholder text

2020-11-10 15:47 UTC, tpoisot requested changes

2020-11-10 15:47 UTC, tpoisot commented on manuscript.md
> +* As this will probably play a part in up setting the tone/concept for the ms
This currently lacks a bit of referencing - you can have a look at the preprint I shared in the github teams, and in particular the Jordano papers from 2016

2020-11-10 15:47 UTC, tpoisot commented on manuscript.md
> +The scarcity of data on species interactions is certainly one of the biggest
Needs a sentence explaining where the scarcity is from: (i) detecting species, (ii) detecting species together, (iii) detecting species interactions

2020-11-10 15:47 UTC, tpoisot commented on manuscript.md
> +barriers in predicting network structure. Machine learning methods, especially deep
You can cite de Aguiar et al about how the interaction sampling issues can lead to biased network structure estimates

2020-11-10 15:47 UTC, tpoisot commented on manuscript.md
> +[@Michalska-Smith2019TelEco].
this is a good point but under-developed - why is it important, and how is it going to help? If it's a starting point, what is next?

2020-11-10 15:47 UTC, tpoisot commented on manuscript.md
> +The scale at which we are able to predict networks are currently limited to
What scale? Space? Taxonomy? Clarify.

2020-11-10 15:47 UTC, tpoisot commented on manuscript.md
> +[@Guimaraes2020StrEco] and acts as a 'lower-limit' at which we
I would cite a bunch of individual-based networks papers here

2020-11-10 15:47 UTC, tpoisot commented on manuscript.md
> +networks at finer scales, although current trends in e.g. remote sensing would
https://www.frontiersin.org/articles/10.3389/fenvs.2019.00197/full and the papers cited therein about interactions should be cited here

2020-11-10 15:49 UTC, tpoisot commented
I have nuked the bibliography file, please re-export

2020-11-10 17:55 UTC, TanyaS08 commented
I have an admin question for @tpoisot - did you 'push' what was in the integration branch for section one into this branch as well but the Section 1 integration branch still exists and when this is a bit more fleshed out it would get merged with that branch? It's late on a Tuesday evening and everything is just a little bit fuzzy...

2020-11-17 16:22 UTC, TanyaS08 commented
I think we're beginning to take the steps from _it exists_ to _its getting functional_. There are still a few points that need to be raised/refined and I'm sure @FrancisBanville will have thoughts™ he's like to add

2020-12-03 03:51 UTC, tpoisot approved these changes

2020-12-07 19:53 UTC, FrancisBanville approved these changes
I think it is ready to be integrated @TanyaS08?

2020-12-08 06:28 UTC, merged