How do we validate a predictive model?
PoisotLab/ms_network_prediction pull request #22
Opened 2020-10-30 20:14 UTC by gottacatchenall

2020-11-04 12:07 UTC, tpoisot commented
I think this is still one question: what are the different approaches to validation and what do they tell us?

2020-11-04 18:29 UTC, gottacatchenall commented
> I think this is still one question: what are the different approaches to validation and what do they tell us?

agreed that would make a better wording for the question, those questions i added are what i'm hoping to address in the answer---we'll see how it goes

2020-11-15 01:35 UTC, gottacatchenall commented
@tpoisot @TanyaS08 this almost ready for review, but i'm looking for citation recommendations and any other comments before i attempt to merge

2020-11-17 01:27 UTC, tpoisot commented
I suggest we merge after a review, and then when we integrate we can look at references. I like the fact that the current set of refs is technical and more hands-on discussions about model validation.

2020-11-17 05:52 UTC, TanyaS08 reviewed
Firstly, this is definitely on the better side of the scale of explaining model comparison/validation. Short and sweet but still informative. I'm assuming the plan is to expand on out of sample prediction? Also (out of curiosity) in one of the previous interactions hind casting was name dropped - is that a ship that has sailed/conversation for another day?

2020-11-18 12:36 UTC, TanyaS08 approved these changes
Happy to integrate as is if the rest of the review squad is

2020-11-18 15:52 UTC, tpoisot requested changes

2020-11-18 15:52 UTC, tpoisot commented on manuscript.md
> +- Out of sample prediction is ideal, but often not possible.
Can we turn this into full sentences?

2020-11-18 15:52 UTC, tpoisot commented on manuscript.md
> +Various forms of crossvalidation exist (k-fold, monte carlo, etc.)---often comes down to computation time limits.
Can we develop this a little bit more?

2020-12-02 16:33 UTC, TanyaS08 commented
@gottacatchenall is this one ready for review - last commit says still in progress os don't want to flag for review juuuuust in case!

2020-12-02 19:58 UTC, gottacatchenall commented
> @gottacatchenall is this one ready for review - last commit says still in progress os don't want to flag for review juuuuust in case!

there may be some minor changes to phrasing i want to make but that can be done at the integration stage---good to merge if you are

2020-12-08 14:28 UTC, merged