Glossary
PoisotLab/ms_network_prediction pull request #38
Opened 2020-11-01 18:32 UTC by gottacatchenall

an empty glossary at the end of manuscript md

2020-11-01 18:34 UTC, gottacatchenall commented
it's possible we will want to assign specific definitions to specific people, not sure how we want to do that to avoid merge conflicts though

2020-11-01 18:41 UTC, TanyaS08 commented
There's a part of me that wants to just relegate flagging terms needed for the glossary to the comments/an issue and then we define and collate later (but that's probably creating unneeded work).  The idea of assigning a specific term to a person could work... Then its just down to internal comms to co-ordinate but I like the proposal of doing something similar to what we are doing with the author details in the metadata file

2020-11-01 18:49 UTC, gottacatchenall commented
> There's a part of me that wants to just relegate flagging terms needed for the glossary to the comments/an issue and then we define and collate later (but that's probably creating unneeded work). 

I agree, I'll make a glossary issue and we can tag people and explain there

2020-11-02 15:09 UTC, tpoisot requested changes

2020-11-02 15:09 UTC, tpoisot commented on manuscript.md
> +## Glossary
I would put this as a box -- markdown has a nice way to write definitions:

~~~
Metaweb
: hella many interactions
~~~

It doesn't work on github markdown, but this should get rendered in the PDF and html

2020-11-03 01:56 UTC, tpoisot commented
One thing we *could* do is `glossary.json` - this would be very easy to render in the template(s), and if this is self-contained to a file, it would make it easier to work on.

~~~ json
[
  {
    "term": "Metaweb",
    "definition": "A lot of interactions"
  },
  {
    "term": "Machine learning",
    "definition": "Essentially magic, but sad"
  },
  {
    "term": "Ecological network",
    "definition": "A community defined by people who wish they were better at maths"
  }
]
~~~

2020-11-03 03:26 UTC, gottacatchenall commented
i like a json glossary idea a lot---assuming those definitions are included, of course

2020-11-03 05:09 UTC, TanyaS08 commented
Have to agree with @gottacatchenall 100% - a suggestion for interactions: how much two species vibe with each other

2020-11-03 13:09 UTC, tpoisot commented
Predation :

![ztHKpje](https://user-images.githubusercontent.com/579329/97989011-e693ef80-1dab-11eb-8534-967f80b54130.jpg)

2020-11-03 16:05 UTC, gottacatchenall commented
i believe this is called a "serval"

![hejustvibin](https://user-images.githubusercontent.com/17133743/98010157-3920dc00-1dab-11eb-9142-f9bdf46c44d5.jpg)

2020-11-03 17:07 UTC, TanyaS08 commented
Hmm something looks off -but I can't quite put my finger on it

2020-11-03 17:41 UTC, gottacatchenall commented
> Hmm something looks off -but I can't quite put my finger on it
bad vibes, probably

2020-11-03 17:44 UTC, TanyaS08 commented
Yeah does not pass the vibe check

2020-11-03 20:31 UTC, gottacatchenall commented
please submit a vibe pull request and we'll take a look

2020-12-03 04:12 UTC, TanyaS08 commented
Flagging forbidden links 🙅‍♀️ here to potentially be included

2021-01-22 14:53 UTC, closed without merging