How much do networks vary in space?
PoisotLab/ms_network_prediction pull request #45
Opened 2020-11-02 19:24 UTC by DominiqueCaron

#4 Recreated a branch + PR to make the name consistent with other branches ("SECTION" instead of "Section")

2020-11-19 19:47 UTC, gottacatchenall reviewed
:+1:

2020-11-19 19:47 UTC, gottacatchenall commented on manuscript.md
>  Networks can vary either in their structural properties (e.g. changes in connectance or degree distribution) or in their composition (e.g. changes in nodes and links identity). Interestingly, variati
> but this variation is mainly explained by the spatial variation in species richness.

I think this probably needs a citation

2020-11-19 19:47 UTC, gottacatchenall commented on manuscript.md
> +On a lower level, species turnover in space obviously results in changes in the composition of ecological networks. But, this is not the only reason networks composition varies [@Poisot2015BeySpe]. I
> Similarly, changes in species abundances can lead to variation in interactions [ADD REF].

I'm thinking [Vasquez et al 2007 in Oikos](http://www.dx.doi.org/10.1111/j.0030-1299.2007.15828.x)

2020-11-19 19:47 UTC, gottacatchenall commented on manuscript.md
>  Networks can vary either in their structural properties (e.g. changes in connectance or degree distribution) or in their composition (e.g. changes in nodes and links identity). Interestingly, variati
> but this variation is mainly explained by the spatial variation in species richness

I think this is the primary point here, could be emphasized at the beginning

2020-11-19 19:47 UTC, gottacatchenall commented on manuscript.md
> +On a lower level, species turnover in space obviously results in changes in the composition of ecological networks. But, this is not the only reason networks composition varies [@Poisot2015BeySpe]. I
> Intraspecific variations can result in interaction turnovers without changes in species composition [ADD REF]. 

I'm thinking [Bolnick et al 2012](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3088364/pdf/nihms285002.pdf)

2020-11-19 19:49 UTC, gottacatchenall requested changes
added a few notes

2020-11-23 10:45 UTC, TanyaS08 reviewed
I really really like this section. It ties/brings together a lot of the points raised earlier in the ms and sets the stage for discussions around space. I wonder if we could/should briefly discuss how much networks vary over different spatial scales...

2020-11-26 17:11 UTC, DominiqueCaron commented
> .

Interesting. Something like discussed in [Galiana et al. 2018](https://www-nature-com.proxy3.library.mcgill.ca/articles/s41559-018-0517-3)? I feel that it is somehow a different question, but still very relevant and related. If we are not discussing it in another section (maybe in the spatial scale of prediction?), and we still have a couple of words we can add, I can surely find a spot to add this! Maybe I'll tweak the question a bit.

2020-11-26 17:35 UTC, TanyaS08 commented
> > I really really like this section. It ties/brings together a lot of the points raised earlier in the ms and sets the stage for discussions around space. I wonder if we could/should briefly discuss how much networks vary over different spatial scales...
> 
> Interesting. Something like discussed in [Galiana et al. 2018](https://www-nature-com.proxy3.library.mcgill.ca/articles/s41559-018-0517-3)? I feel that it is somehow a different question, but still very relevant and related. If we are not discussing it in another section (maybe in the spatial scale of prediction?), and we still have a couple of words we can add, I can surely find a spot to add this! Maybe I'll tweak the question a bit.

Firstly ref = A+ in terms of direction of thinking. I think you're right that it might be better suited to a different section but maybe something we can flag/keep in mind when we start integrating and include where needed?

2020-11-26 18:12 UTC, gottacatchenall approved these changes

2020-11-26 18:45 UTC, TanyaS08 approved these changes

2020-11-27 07:08 UTC, merged